### ISSUE TITLE
Prior hi-scores are not being found/recognized after v2.0 upgrade

### ISSUE THREAD

**Issue by daveahmadi** [retro-center/rcade_releases#46]
**Describe the bug**
R-Cade v2.0 release is not recognizing high scores from v1.1.1 after upgrade. New hi-score files are being created in a different directory structure.

v1.1.1 saves directory structure
\\rcade\share\saves\\[core name]\\
examples:
\\rcade\share\saves\fbneo\
\\rcade\share\saves\mame2003-plus\
\\rcade\share\saves\mame2010\

v2.0 saves directory structure
\\rcade\share\saves\\[long core name]\\[core name]\\
examples:
\\rcade\share\saves\FinalBurn Neo\fbneo\
\\rcade\share\saves\MAME 2003-Plus\mame2003-plus\
\\rcade\share\saves\MAME 2010\mame2010\

I don't save game states, but this may impact the ability for users to find old save state files as well.

**To Reproduce**

**Expected behavior**
Save files should persist between versions. New saves should be in same directory as prior release or prior release save files should be moved into new directory structure during upgrade.

**Environment (please complete the following information):**
 - R-Cade Version: 2.0
 - Board: ALU 1.2 
 - OS Disk

**Comment by retro-center** [comment]
Thank you for reporting this!
The issue is actually due to a change in retroarch, outlined here:
https://github.com/libretro/RetroArch/issues/16430#issuecomment-2049230237

I have adjusted the default values in v2.0.1 so that the two retroarch settings are the way they were before.
If these values are enabled, you will want to copy the old folder into the new folder to restore your missing high scores.
